name: Build and Deploy

on:
  push:
    branches:
      - gh-pages
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened

  workflow_dispatch:

concurrency: preview-${{ github.ref }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install and Build
        run: |
          npm install
          npm ci
          npm run lint
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build

  deploy-preview:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/
