name: Build and Deploy ph-pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

concurrency: preview-${{ github.ref }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install and Build
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
        run: |
          yarn install --frozen-lockfile
          yarn run lint
          yarn run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
