name: Build and Deploy ph-pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:

    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pull-requests: write
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install and Build
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          yarn install --frozen-lockfile
          yarn run lint
          yarn run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
